### ISSUE TITLE
Layout best practices

### ISSUE THREAD

**Issue by varit** [varit/waterfall#5]
## Unexpected Behavior

What is the best approach in setting up the Layout.jsx if the  information inside <header> changes between screen? ie <div>AppName</div> to <div>Username</div>

## Expected Behavior

Layout that can have its content change dynamically while preserving the overall layout

## Reproduce the Error

N/A

## Documentation

N/A

## Attempted Resolution

https://blog.logrocket.com/the-best-styling-in-react-tutorial-youve-ever-seen-676f1284b945/

**Comment by zulays** [comment]
@varit I would suggest using a ternery statement. you can change the div depending of the state of the user, something like
`{ !currentUser ? <div>AppName</div> : <div>userName</div>  }`
